services:
  modm:
    env_file: ../bin/.env
    image: modmapi:latest
    volumes:
      - "${HOME}/.azure:/root/.azure"
      - "${HOME}/tmp:/tmp"
    ports:
      - 8080:8080
    environment:
      - GO_ENV=development
      - MODM_PUBLIC_BASE_URL=${MODM_PUBLIC_BASE_URL}
      - MODM_LOG_FILE_PATH=/tmp
    networks:
      - web
  modmoperator:
    env_file: ../bin/.env
    image: modmoperator:latest
    environment:
      - GO_ENV=development
    networks:
      - web

networks:
  web:
    external: true
