services:
  modm:
    env_file: ../bin/.env
    image: modm:latest
    volumes:
      - "${HOME}/.azure:/root/.azure"
    ports:
      - 8080:8080
    environment:
      - GO_ENV=development
      - PUBLIC_DOMAIN_NAME=${PUBLIC_DOMAIN_NAME}
    networks:
      - web

networks:
  web:
    external: true
