services:
  web:
    env_file: ../bin/.env
    image: modm:latest
    ports:
      - "8080:8080"
    environment:
      - HTTPS=false
      - PUBLIC_DOMAIN_NAME=
    volumes:
      - ../deployments/certs:/app/certs