services:
  modm:
    profiles:
      - "local"
    image: modm:latest
    container_name: modm
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - MODM_HOME=/usr/local/modm
    volumes:
      - ~/.azure:/root/.azure
      - ${MODM_HOME}:/usr/local/modm
      - ./:/usr/local/modm/source
  jenkins:
    profiles:
      - "local"
      - "jenkins"
    image: jenkins:latest
    container_name: jenkins
    ports:
      - 8080:8080
    volumes:
      - ~/.azure:/root/.azure
      - ${MODM_HOME}:/var/jenkins_home/modm
      - ./:/var/jenkins_home/modm/source
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - DEFAULT_ADMIN_PASSWORD=admin
      - AZURE_SUBSCRIPTION_ID=$AZURE_SUBSCRIPTION_ID
      - AZURE_CLIENT_ID=$AZURE_CLIENT_ID
      - AZURE_CLIENT_SECRET=$AZURE_CLIENT_SECRET
      - AZURE_TENANT_ID=$AZURE_TENANT_ID
      - MODM_HOME=/var/jenkins_home/modm
