/*
 * Marketplace Offer Deployment Management
 *
 * Commercial Marketplace deployment management for azure offers.
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package apiserver

import (
	"log"
	"net/http"

	"github.com/microsoft/commercial-marketplace-offer-deploy/cmd/apiserver/routes"
)

func main() {
	log.Printf("Server started")

	router := routes.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
