//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package sdk

type AvailableDeploymentOperation struct {
	Name *string `json:"name,omitempty"`
	Parameters []*string `json:"parameters,omitempty"`
}

type Deployment struct {
	ID *int64 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Stages []*DeploymentStage `json:"stages,omitempty"`
	Template *DeploymentTemplate `json:"template,omitempty"`
}

type DeploymentOperation struct {
	Name *string `json:"name,omitempty"`
	Parameters []*DeploymentOperationParameter `json:"parameters,omitempty"`
}

type DeploymentOperationParameter struct {
	Name *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

type DeploymentRequest struct {
	// REQUIRED
	Name *string `json:"name,omitempty"`
	MultiStage *bool `json:"multiStage,omitempty"`
	Template *DeploymentTemplate `json:"template,omitempty"`
}

type DeploymentStage struct {
	// Dictionary of
	Attributes map[string]any `json:"attributes,omitempty"`
	Name *string `json:"name,omitempty"`
}

type DeploymentTemplate struct {
	Name *string `json:"name,omitempty"`
	Parameters []*DeploymentTemplateParameter `json:"parameters,omitempty"`
	URI *string `json:"uri,omitempty"`
}

type DeploymentTemplateParameter struct {
	Name *string `json:"name,omitempty"`

	// Dictionary of
	Value map[string]any `json:"value,omitempty"`
}

type Event struct {
	Name *string `json:"name,omitempty"`
}

type EventSubscription struct {
	Callback *string `json:"callback,omitempty"`
	Name *string `json:"name,omitempty"`
	Topic *string `json:"topic,omitempty"`
}

// MarketplaceOfferDeploymentManagerClientAddDeploymentOptions contains the optional parameters for the marketplaceOfferDeploymentManagerClient.AddDeployment
// method.
type MarketplaceOfferDeploymentManagerClientAddDeploymentOptions struct {
	// placeholder for future optional parameters
}

// MarketplaceOfferDeploymentManagerClientAddEventSubscriptionOptions contains the optional parameters for the marketplaceOfferDeploymentManagerClient.AddEventSubscription
// method.
type MarketplaceOfferDeploymentManagerClientAddEventSubscriptionOptions struct {
	// placeholder for future optional parameters
}

// MarketplaceOfferDeploymentManagerClientGetDeploymentByIDOptions contains the optional parameters for the marketplaceOfferDeploymentManagerClient.GetDeploymentByID
// method.
type MarketplaceOfferDeploymentManagerClientGetDeploymentByIDOptions struct {
	// placeholder for future optional parameters
}

// MarketplaceOfferDeploymentManagerClientGetDeploymentsOptions contains the optional parameters for the marketplaceOfferDeploymentManagerClient.GetDeployments
// method.
type MarketplaceOfferDeploymentManagerClientGetDeploymentsOptions struct {
	// Status values that need to be considered for filter
	Status []Get0ItemsItem
}

// MarketplaceOfferDeploymentManagerClientGetEventsOptions contains the optional parameters for the marketplaceOfferDeploymentManagerClient.GetEvents
// method.
type MarketplaceOfferDeploymentManagerClientGetEventsOptions struct {
	// placeholder for future optional parameters
}

// MarketplaceOfferDeploymentManagerClientGetOperationsOptions contains the optional parameters for the marketplaceOfferDeploymentManagerClient.GetOperations
// method.
type MarketplaceOfferDeploymentManagerClientGetOperationsOptions struct {
	// placeholder for future optional parameters
}

// MarketplaceOfferDeploymentManagerClientTriggerDeploymentOperationOptions contains the optional parameters for the marketplaceOfferDeploymentManagerClient.TriggerDeploymentOperation
// method.
type MarketplaceOfferDeploymentManagerClientTriggerDeploymentOperationOptions struct {
	// placeholder for future optional parameters
}

// MarketplaceOfferDeploymentManagerClientUpdateDeploymentOptions contains the optional parameters for the marketplaceOfferDeploymentManagerClient.UpdateDeployment
// method.
type MarketplaceOfferDeploymentManagerClientUpdateDeploymentOptions struct {
	// placeholder for future optional parameters
}

