//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package sdk

// MarketplaceOfferDeploymentManagerClientAddDeploymentResponse contains the response from method marketplaceOfferDeploymentManagerClient.AddDeployment.
type MarketplaceOfferDeploymentManagerClientAddDeploymentResponse struct {
	// placeholder for future response values
}

// MarketplaceOfferDeploymentManagerClientAddEventSubscriptionResponse contains the response from method marketplaceOfferDeploymentManagerClient.AddEventSubscription.
type MarketplaceOfferDeploymentManagerClientAddEventSubscriptionResponse struct {
	// placeholder for future response values
}

// MarketplaceOfferDeploymentManagerClientGetDeploymentByIDResponse contains the response from method marketplaceOfferDeploymentManagerClient.GetDeploymentByID.
type MarketplaceOfferDeploymentManagerClientGetDeploymentByIDResponse struct {
	Deployment
}

// MarketplaceOfferDeploymentManagerClientGetDeploymentsResponse contains the response from method marketplaceOfferDeploymentManagerClient.GetDeployments.
type MarketplaceOfferDeploymentManagerClientGetDeploymentsResponse struct {
	// Array of Deployment
	DeploymentArray []*Deployment
}

// MarketplaceOfferDeploymentManagerClientGetEventsResponse contains the response from method marketplaceOfferDeploymentManagerClient.GetEvents.
type MarketplaceOfferDeploymentManagerClientGetEventsResponse struct {
	// Array of AvailableDeploymentOperation
	AvailableDeploymentOperationArray []*AvailableDeploymentOperation
}

// MarketplaceOfferDeploymentManagerClientGetOperationsResponse contains the response from method marketplaceOfferDeploymentManagerClient.GetOperations.
type MarketplaceOfferDeploymentManagerClientGetOperationsResponse struct {
	// Array of AvailableDeploymentOperation
	AvailableDeploymentOperationArray []*AvailableDeploymentOperation
}

// MarketplaceOfferDeploymentManagerClientTriggerDeploymentOperationResponse contains the response from method marketplaceOfferDeploymentManagerClient.TriggerDeploymentOperation.
type MarketplaceOfferDeploymentManagerClientTriggerDeploymentOperationResponse struct {
	// placeholder for future response values
}

// MarketplaceOfferDeploymentManagerClientUpdateDeploymentResponse contains the response from method marketplaceOfferDeploymentManagerClient.UpdateDeployment.
type MarketplaceOfferDeploymentManagerClientUpdateDeploymentResponse struct {
	// placeholder for future response values
}

