//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package sdk

import "time"

type CreateDeployment struct {
	// REQUIRED
	Name *string `json:"name,omitempty"`

	// REQUIRED; Anything
	Template any `json:"template,omitempty"`
	Location *string `json:"location,omitempty"`
	ResourceGroup *string `json:"resourceGroup,omitempty"`
	SubscriptionID *string `json:"subscriptionId,omitempty"`
}

type CreateEventHookRequest struct {
	// API key to be used in the Authorization header, e.g. 'apiKey =234dfsdf324234', to call the webhook callback URL.
	APIKey *string `json:"apiKey,omitempty"`

	// The webhook callback
	Callback *string `json:"callback,omitempty"`

	// the name of the subscription
	Name *string `json:"name,omitempty"`
}

type CreateEventHookResponse struct {
	ID *string `json:"id,omitempty"`

	// the name of the subscription
	Name *string `json:"name,omitempty"`
}

type Deployment struct {
	ID *int32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Stages []*DeploymentStage `json:"stages,omitempty"`
	Status *string `json:"status,omitempty"`

	// Anything
	Template any `json:"template,omitempty"`
}

// DeploymentManagementClientCreateDeploymentOptions contains the optional parameters for the DeploymentManagementClient.CreateDeployment
// method.
type DeploymentManagementClientCreateDeploymentOptions struct {
	// placeholder for future optional parameters
}

// DeploymentManagementClientCreateEvenHookOptions contains the optional parameters for the DeploymentManagementClient.CreateEvenHook
// method.
type DeploymentManagementClientCreateEvenHookOptions struct {
	// placeholder for future optional parameters
}

// DeploymentManagementClientDeleteEventHookOptions contains the optional parameters for the DeploymentManagementClient.DeleteEventHook
// method.
type DeploymentManagementClientDeleteEventHookOptions struct {
	// placeholder for future optional parameters
}

// DeploymentManagementClientGetDeploymentOptions contains the optional parameters for the DeploymentManagementClient.GetDeployment
// method.
type DeploymentManagementClientGetDeploymentOptions struct {
	// placeholder for future optional parameters
}

// DeploymentManagementClientGetEventHookOptions contains the optional parameters for the DeploymentManagementClient.GetEventHook
// method.
type DeploymentManagementClientGetEventHookOptions struct {
	// placeholder for future optional parameters
}

// DeploymentManagementClientGetEventTypesOptions contains the optional parameters for the DeploymentManagementClient.GetEventTypes
// method.
type DeploymentManagementClientGetEventTypesOptions struct {
	// placeholder for future optional parameters
}

// DeploymentManagementClientGetHealthOptions contains the optional parameters for the DeploymentManagementClient.GetHealth
// method.
type DeploymentManagementClientGetHealthOptions struct {
	// placeholder for future optional parameters
}

// DeploymentManagementClientGetInvokedDeploymentOperationOptions contains the optional parameters for the DeploymentManagementClient.GetInvokedDeploymentOperation
// method.
type DeploymentManagementClientGetInvokedDeploymentOperationOptions struct {
	// placeholder for future optional parameters
}

// DeploymentManagementClientInvokeDeploymentOperationOptions contains the optional parameters for the DeploymentManagementClient.InvokeDeploymentOperation
// method.
type DeploymentManagementClientInvokeDeploymentOperationOptions struct {
	// placeholder for future optional parameters
}

// DeploymentManagementClientListDeploymentsOptions contains the optional parameters for the DeploymentManagementClient.ListDeployments
// method.
type DeploymentManagementClientListDeploymentsOptions struct {
	// Status values that need to be considered for filter
	Status []Status
}

// DeploymentManagementClientListEventHooksOptions contains the optional parameters for the DeploymentManagementClient.ListEventHooks
// method.
type DeploymentManagementClientListEventHooksOptions struct {
	// placeholder for future optional parameters
}

// DeploymentManagementClientListInvokedOperationsOptions contains the optional parameters for the DeploymentManagementClient.ListInvokedOperations
// method.
type DeploymentManagementClientListInvokedOperationsOptions struct {
	// placeholder for future optional parameters
}

// DeploymentManagementClientUpdateDeploymentOptions contains the optional parameters for the DeploymentManagementClient.UpdateDeployment
// method.
type DeploymentManagementClientUpdateDeploymentOptions struct {
	// placeholder for future optional parameters
}

type DeploymentStage struct {
	DeploymentName *string `json:"deploymentName,omitempty"`
	ID *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`

	// the default number of retries. can be set with tag modm.retry. defaults to 0.
	Retries *int32 `json:"retries,omitempty"`
}

type EventHookResponse struct {
	// The webhook callback
	Callback *string `json:"callback,omitempty"`
	ID *string `json:"id,omitempty"`

	// the name of the subscription
	Name *string `json:"name,omitempty"`
}

type EventType struct {
	// The type of event, e.g. the topic
	Name *string `json:"name,omitempty"`
}

type GetHealthResponse struct {
	// REQUIRED
	IsHealthy *bool `json:"isHealthy,omitempty"`
}

type GetInvokedOperationResponse struct {
	// An invoked operation
	InvokedOperation *InvokedOperation `json:"invokedOperation,omitempty"`
}

type InvokeDeploymentOperationRequest struct {
	Name *string `json:"name,omitempty"`

	// Anything
	Parameters any `json:"parameters,omitempty"`
	Retries *int32 `json:"retries,omitempty"`

	// whether the call wants to wait for the operation or if the result of the invocation will be received async from an event
// susbscription
	Wait *bool `json:"wait,omitempty"`
}

type InvokedDeploymentOperationResponse struct {
	// An invoked operation
	InvokedOperation *InvokedOperation `json:"invokedOperation,omitempty"`
}

// InvokedOperation - An invoked operation
type InvokedOperation struct {
	Attempts *int32 `json:"attempts,omitempty"`

	// the associated deployment ID if the operation was invoked against a deployment
	DeploymentID *int32 `json:"deploymentId,omitempty"`
	ID *string `json:"id,omitempty"`
	InvokedOn *time.Time `json:"invokedOn,omitempty"`
	Name *string `json:"name,omitempty"`

	// Anything
	Parameters any `json:"parameters,omitempty"`

	// Anything
	Result any `json:"result,omitempty"`
	Retries *int32 `json:"retries,omitempty"`
	Status *string `json:"status,omitempty"`
}

// ListInvokedOperationResponse - List response of invoked operations
type ListInvokedOperationResponse struct {
	Items []*InvokedOperation `json:"items,omitempty"`
}

