//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package sdk

type Status string

const (
	StatusCanceled Status = "canceled"
	StatusError Status = "error"
	StatusFailed Status = "failed"
	StatusRunning Status = "running"
	StatusScheduled Status = "scheduled"
	StatusSuccess Status = "success"
	StatusUnknown Status = "unknown"
)

// PossibleStatusValues returns the possible values for the Status const type.
func PossibleStatusValues() []Status {
	return []Status{	
		StatusCanceled,
		StatusError,
		StatusFailed,
		StatusRunning,
		StatusScheduled,
		StatusSuccess,
		StatusUnknown,
	}
}

