# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CD

env:
  targetGitHubAccount: gpsuscodewith
  versionPrefix: v0.1.
  imageName: modm
  RESOURCE_GROUP_NAME: development-${{ github.run_number }}
on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build binaries
      run: make build
  
  push:     
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.CR_PAT2 }} | docker login ghcr.io -u ${{ env.targetGitHubAccount }} --password-stdin
    - name: Build and push to registry
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        file: ./build/package/Dockerfile
        tags: ghcr.io/${{ env.targetGitHubAccount }}/${{ env.imageName }}:latest, ghcr.io/${{ env.targetGitHubAccount }}/${{ env.imageName }}:${{ env.versionPrefix }}${{github.run_number}}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false

  azure-deploy:
    runs-on: ubuntu-latest
    needs: [push]
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Clean up resource groups
        uses: azure/CLI@v1 
        with: 
          azcliversion: 2.30.0 
          inlineScript: | 
            filter="[?starts_with(name,'development')].[name]" 
            groups=$(az group list --query $filter -o tsv) 
            for g in $groups; do 
              az group delete -n $g --yes --no-wait; 
            done 
            az group create -l eastus -n $RESOURCE_GROUP_NAME

      # Replace the placeholder registry password with secret
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "<placeholderRegistryPassword>"
          replace: "${{ secrets.CR_PAT2 }}"
          include: "templates/**"
          regex: true

      - name: Deploy resources
        uses: azure/CLI@v1 
        with: 
          azcliversion: 2.30.0 
          inlineScript: |
            cd ./templates 
            az deployment group create --resource-group $RESOURCE_GROUP_NAME \
                --template-file ./main.bicep \
                --parameters acmeEmail=nowhere@domain.com appVersion=v0.1.${{github.run_number}}
