# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "feature/ci" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Populate devTest config file from secrets
      run: |
        echo "testing" > ./cmd/apiserver/config.json

    - name: Build apiserver
      run: make apiserver

    - name: Test apiserver
      run: make apiserver-test

    - name: Build operator
      run: make operator
    
    - name: Test operator
      run: make operator-test

    - name: Show json file
      run: cat ./cmd/apiserver/config.json
