# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

env:
  targetGitHubAccount: gpsuscodewith
  versionPrefix: v0.1.
  imageName: modm

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build apiserver
      run: make apiserver
      
    - name: Echo secrets
      run: |
          echo ${{secrets.ENV}} >> ./bin/.env
        
    - name: Show configs
      run: cat ./bin/.env
      
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build operator
      run: make operator
    
    # - name: Run tests
    # run: make test-all
          
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.CR_PAT2 }} | docker login ghcr.io -u ${{ env.targetGitHubAccount }} --password-stdin
    - name: Build and push to registry
      uses: docker/build-push-action@v4
      with:
        context: ./build/package
        push: true
        tags: ghcr.io/${{ env.targetGitHubAccount }}/${{ env.imageName }}:${{ env.versionPrefix }}${{github.run_number}}
