# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build apiserver
      run: make apiserver
      
    - name: Echo secrets
      run: |
          echo $ENV_SECRET >> ./bin/.env
          cat ./bin/.env
      shell: bash
      env:
        ENV_SECRET : ${{secrets.ENV}}

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build operator
      run: make operator
    
    - name: Run tests
      run: make test-all
      
    - name: Show configs
      run: cat ./bin/.env
