name: MODM Base Packer Build

on:
    workflow_dispatch:

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Azure Login
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Get Latest Azure CLI
          id: get_latest_version
          uses: azure/CLI@v1
          with:
            azcliversion: 2.34.1
            inlineScript: |
                az account show
                az storage -h
        
        - name: Install Packer
          uses: hashicorp/packer-github-actions@master
          with:
            version: "1.9.2"

        - name: Set up environment
          run: |
                echo "PKR_VAR_client_id=${{ secrets.PKR_VAR_client_id }}" >> $GITHUB_ENV
                echo "PKR_VAR_client_secret=${{ secrets.PKR_VAR_client_secret }}" >> $GITHUB_ENV
                echo "PKR_VAR_managed_image_name=${{ secrets.PKR_VAR_managed_image_name }}" >> $GITHUB_ENV
                echo "PKR_VAR_subscription_id=${{ secrets.PKR_VAR_subscription_id }}" >> $GITHUB_ENV
                echo "PKR_VAR_tenant_id=${{ secrets.PKR_VAR_tenant_id }}" >> $GITHUB_ENV
                echo "PKR_VAR_location=${{ secrets.PKR_VAR_location }}" >> $GITHUB_ENV
                echo "PKR_VAR_sig_gallery_resource_group=${{ secrets.PKR_VAR_sig_gallery_resource_group }}" >> $GITHUB_ENV
                echo "PKR_VAR_sig_gallery_name=${{ secrets.PKR_VAR_sig_gallery_name }}" >> $GITHUB_ENV
                echo "PKR_VAR_sig_image_name=${{ secrets.PKR_VAR_sig_image_name }}" >> $GITHUB_ENV
                echo "PKR_VAR_sig_image_name_modm=${{ secrets.PKR_VAR_sig_image_name_modm }}" >> $GITHUB_ENV
                echo "PKR_VAR_managed_image_name_modm=${{ secrets.PKR_VAR_managed_image_name_modm }}" >> $GITHUB_ENV
                echo "PKR_VAR_managed_image_resource_group_modm=${{ secrets.PKR_VAR_managed_image_resource_group_modm }}" >> $GITHUB_ENV
                echo "PKR_VAR_managed_image_resource_group_name=${{ secrets.PKR_VAR_managed_image_resource_group_name }}" >> $GITHUB_ENV
                echo "PKR_VAR_custom_managed_image_name=${{ secrets.PKR_VAR_custom_managed_image_name }}" >> $GITHUB_ENV
          env:
                PKR_VAR_client_id: ${{ secrets.PKR_VAR_client_id }}
                PKR_VAR_client_secret: ${{ secrets.PKR_VAR_client_secret }}
                PKR_VAR_managed_image_name: ${{ secrets.PKR_VAR_managed_image_name }}
                PKR_VAR_subscription_id: ${{ secrets.PKR_VAR_subscription_id }}
                PKR_VAR_tenant_id: ${{ secrets.PKR_VAR_tenant_id }}
                PKR_VAR_location: ${{ secrets.PKR_VAR_location }}
                PKR_VAR_sig_gallery_resource_group: ${{ secrets.PKR_VAR_sig_gallery_resource_group }}
                PKR_VAR_sig_gallery_name: ${{ secrets.PKR_VAR_sig_gallery_name }}
                PKR_VAR_sig_image_name: ${{ secrets.PKR_VAR_sig_image_name }}
                PKR_VAR_sig_image_name_modm: ${{ secrets.PKR_VAR_sig_image_name_modm }}
                PKR_VAR_managed_image_name_modm: ${{ secrets.PKR_VAR_managed_image_name_modm }}
                PKR_VAR_managed_image_resource_group_modm: ${{ secrets.PKR_VAR_managed_image_resource_group_modm }}
                PKR_VAR_managed_image_resource_group_name: ${{ secrets.PKR_VAR_managed_image_resource_group_name }}
                PKR_VAR_custom_managed_image_name: ${{ secrets.PKR_VAR_custom_managed_image_name }}

        - name: Run Packer script
          run: |
            chmod +x ./build/base/modm/build.sh
            ./build/vmi/base/build.sh ${{ secrets.MODM_VERSION }}